import tkinter as tk
root = tk.Tk()
tk.Label(root, text='Click at different\n locations in the frame below').pack()
def callback(event):
    print(dir(event))
    print("you clicked at", event.x, event.y)
frame = tk.Frame(root, bg = 'khaki', width=130, height=80)
frame.bind("<Button-1>", callback)
frame.bind("<Button-2>", callback)
frame.bind("<Return>", callback)
frame.bind("<FocusIn>", callback)
frame.bind("<KeyPress-A>", callback)
frame.bind("<KeyPress-Caps_Lock>", callback)
frame.bind("<KeyPress-F1>", callback)
frame.bind("<KeyPress-KP_5>", callback)
frame.bind("<Motion>", callback)
frame.bind("<Any-KeyPress>", callback)
frame.pack()
root.mainloop()
